version: '3.8'

services:
  livechat:
    build: ./livechat
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped
  tournamentapi:
    build: ./lobby
    ports:
    - "3001:3001"
    working_dir: /app
    restart: unless-stopped